apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-local-dns.fullname" . }}-metrics
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "node-local-dns.selectorLabels" . | nindent 4 }}
