name: Cleanup

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  metadata-collector:
    uses: ./.github/workflows/metadata-collector.yaml

  packages:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: metadata-collector
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJSON(needs.metadata-collector.outputs.charts) }}
    steps:
      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@955b5ba4560860f8a633bd24190941f16016e42c # v5.1.0

      - name: Cleanup Helm chart
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/${PACKAGE_NAME} || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_NAME: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}%2F${{ env.GITHUB_EVENT_REF_SLUG_URL || env.GITHUB_HEAD_REF_SLUG_URL }}%2F${{ matrix.chart }}
