name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - charts/**

permissions:
  contents: read

env:
  # renovate: datasource=github-releases depName=helm/helm
  HELM_VERSION: v3.18.6

jobs:
  metadata-collector:
    uses: ./.github/workflows/metadata-collector.yaml

  chart:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: metadata-collector
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJSON(needs.metadata-collector.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up ORAS
        uses: oras-project/setup-oras@8d34698a59f5ffe24821f0b48ab62a3de8b64b20 # v1.2.3

      - name: Publish Helm chart
        # FIXME config: Add dependency repositories
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${GITHUB_ACTOR} --password-stdin

          helm dependency build charts/${CHART_NAME}
          helm package charts/${CHART_NAME}
          helm push "$(realpath ${CHART_NAME}-*.tgz)" oci://ghcr.io/${REPOSITORY_NAME}

          helm registry logout ghcr.io
        env:
          REPOSITORY_NAME: ${{ github.repository }}
          CHART_NAME: ${{ matrix.chart }}

      - name: Update ArtifactHUB repo
        if: ${{ hashFiles(format('charts/{0}/artifacthub-repo.yml', matrix.chart)) != '' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io --username ${GITHUB_ACTOR} --password-stdin

          oras push ghcr.io/${REPOSITORY_NAME}/${CHART_NAME}:artifacthub.io \
            --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
            charts/${CHART_NAME}/artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml

          oras logout ghcr.io
        env:
          REPOSITORY_NAME: ${{ github.repository }}
          CHART_NAME: ${{ matrix.chart }}
